### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by creater-zq** [xdeng7/NightLab#3]
* 我从[TIP2021_NightCity](https://dmcv.sjtu.edu.cn/people/phd/tanxin/NightCity/index.html)下载的数据集，里面训练图片为2997张，验证为1300张。但是论文中为2998张训练，1299张验证，请问是我下载错误了吗？

**Comment by xdeng7** [comment]
你是从这个链接下载的数据集吗？（https://dmcv.sjtu.edu.cn/people/phd/tanxin/NightCity/index.html）
我用的数据集版本是作者去年给我的，不清楚现在的这个是否更新了，你联系一下原文的作者确认一下，然后麻烦告诉我一声，我把val set的gt更新一下

**Comment by creater-zq** [comment]
是这里的，同时我也下载了你们重新标注的val，打开文件看，也是1300张，是我搞错了吗？


| |
张取
|
|
***@***.***
|
在2022年5月4日 02:10，Xueqing ***@***.***> 写道：

你是从这个链接下载的数据集吗？（https://dmcv.sjtu.edu.cn/people/phd/tanxin/NightCity/index.html）
我用的数据集版本是作者去年给我的，不清楚现在的这个是否更新了，你联系一下原文的作者确认一下，然后麻烦告诉我一声，我把val set的gt更新一下

**Comment by xdeng7** [comment]
> 是这里的，同时我也下载了你们重新标注的val，打开文件看，也是1300张，是我搞错了吗？ | | 张取 | | ***@***.*** | 在2022年5月4日 02:10，Xueqing ***@***.***> 写道： 你是从这个链接下载的数据集吗？（https://dmcv.sjtu.edu.cn/people/phd/tanxin/NightCity/index.html） 我用的数据集版本是作者去年给我的，不清楚现在的这个是否更新了，你联系一下原文的作者确认一下，然后麻烦告诉我一声，我把val set的gt更新一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我应该是用的旧的数据集，你这个数据集应该没错，我查看了我的实验的log，split就是2998 和1299， 你按照新的来就可以
<img width="641" alt="image" src="https://user-images.githubusercontent.com/43100519/166626732-1041d9f7-83d4-455c-8ff8-2a43174eb4ff.png">

**Comment by creater-zq** [comment]
我问作者了，他说是他后来上传的文件搞错了，他会尽快改正的，是2998和1299的，对的。谢谢了


| |
张取
|
|
***@***.***
|
在2022年5月4日 13:22，Xueqing ***@***.***> 写道：

是这里的，同时我也下载了你们重新标注的val，打开文件看，也是1300张，是我搞错了吗？ | | 张取 | | @.*** | 在2022年5月4日 02:10，Xueqing @.> 写道： 你是从这个链接下载的数据集吗？（https://dmcv.sjtu.edu.cn/people/phd/tanxin/NightCity/index.html） 我用的数据集版本是作者去年给我的，不清楚现在的这个是否更新了，你联系一下原文的作者确认一下，然后麻烦告诉我一声，我把val set的gt更新一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

我应该是用的旧的数据集，你这个数据集应该没错，我查看了我的实验的log，split就是2998 和1299， 你按照新的来就可以

**Comment by creater-zq** [comment]
作者已经重新上传了。



---- 回复的原邮件 ----
| 发件人 | Xueqing ***@***.***> |
| 日期 | 2022年05月04日 13:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [xdeng7/NightLab] 数据集 (Issue #3) |

是这里的，同时我也下载了你们重新标注的val，打开文件看，也是1300张，是我搞错了吗？ | | 张取 | | @.*** | 在2022年5月4日 02:10，Xueqing @.> 写道： 你是从这个链接下载的数据集吗？（https://dmcv.sjtu.edu.cn/people/phd/tanxin/NightCity/index.html） 我用的数据集版本是作者去年给我的，不清楚现在的这个是否更新了，你联系一下原文的作者确认一下，然后麻烦告诉我一声，我把val set的gt更新一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

我应该是用的旧的数据集，你这个数据集应该没错，我查看了我的实验的log，split就是2998 和1299， 你按照新的来就可以
